version: '3'
services:
  pokedex-api:
    container_name: pokedex-api
    build: .
    image: nodejs
    restart: always
    env_file: ./.env
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - ES_HOST=elasticsearch
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - PORT=3000
    volumes:
      - .:/usr/src/app/server
      - node_modules:/usr/src/app/server/node_modules
    links:
      - mongodb
      - es01
      - es02
    networks:
      - pokedex-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file: ./.env
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/usr/src/app/data/db
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/usr/src/app/data/db
    networks:
      - pokedex-network

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - pokedex-network
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - pokedex-network

volumes:
  esdata01:
  esdata02:
  mongodata:
  node_modules:

networks:
  pokedex-network:
    driver: bridge